### ISSUE TITLE
Personal settings.

### ISSUE THREAD

**Issue by GrandLTU** [ongr-io/SettingsBundle#121]
In example configuration profiles are provided but no information how to use them or how they work.

Also a general format of setting definition with all fields explained could be usefull.
Example
``` yaml
parameters:
  ongr_settings.settings.categories: # Define your categories here.
    category_1: # Category definition. This name used when defining settings.
      name: Category 1 # Name of the category. Displayed for the user.(Can i translate this?)
      description: cat_desc_1 # Description of the category (optional). Displayed for the user.(Can i translate this?)
```
``` yaml
parameters:
  ongr_settings.settings.settings: # Define your settings here.
    foo_setting_1: # Setting definition. This name is used to access the setting.
      name: Setting 1 # Name of the setting. Displayed for the user.(Can i translate this?)
      category: category_1 # Sets setting category. Defined above.
      description: foo_desc_1 # Description of the category. Displayed for the user.(Can i translate this?)
      cookie: project.cookie.alternative_settings # Optional. Setting will be stored in separate cookie. Value is cookie service name.
```
