### ISSUE TITLE
Services formatting

### ISSUE THREAD

**Issue by tautrimas** [ongr-io/SettingsBundle#51]
- [ ] Ensure all YAML formatting has spaces between braces. E.g.

``` yaml
- [setContainer, [@service_container]]
```

Should be:

``` yaml
- [ setContainer, [ @service_container ] ]
```
- [ ] Mmake sure intendation is correct everywhere (4 spaces). See connections bundle for examples. Bad code:

``` yaml
        calls:
            - [setAdminSettingsManager, [@ongr_admin.settings.admin_settings_manager]]
            - [setContainer, [@service_container]]
        tags:
          - name: kernel.event_listener
            event: kernel.request
            method: onKernelRequest
            priority: 6
```
- [ ] Make sure commenting style is the same everywhere. Space after `#` and dot at the end of sentence.
